[package]
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name = "runtime-common"
version = "0.9.81-dev"
authors = ["Setheum Developers"]
edition = "2021"

[dependencies]
static_assertions = "1.1.0"
num_enum = { version = "0.5.1", default-features = false }
serde = { version = "1.0.101", optional = true, default-features = false }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
ethabi = { version = "15.0.0", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.10" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.10" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.10" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.10" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.10" }
pallet-scheduler = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.10" }
log = { version = "0.4.14", default-features = false }
pallet-collective = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10", default-features = false }
pallet-membership = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10", default-features = false }

orml-oracle = { path = "../../runtime-modules/oracle", default-features = false }
orml-traits = { path = "../../runtime-modules/traits", default-features = false }

module-evm = { path = "../../runtime-modules/evm", default-features = false }
module-support = { path = "../../runtime-modules/support", default-features = false }
module-transaction-payment = { path = "../../runtime-modules/transaction-payment", default-features = false }
primitives = { package = "setheum-primitives", path = "../../primitives", default-features = false }
primitives-proc-macro = { path = "../../primitives/proc-macro" }

[dev-dependencies]
serde_json = "1.0.41"
hex-literal = "0.3.1"
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
pallet-proxy = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
pallet-utility = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }

orml-tokens = { path = "../../runtime-modules/tokens" }
orml-nft = { path = "../../runtime-modules/orml-nft" }

module-currencies = { path = "../../runtime-modules/currencies" }
module-evm-bridge = { path = "../../runtime-modules/evm-bridge" }
module-evm-manager = { path = "../../runtime-modules/evm-manager" }
module-nft = { path = "../../runtime-modules/nft" }
# module-dex = { path = "../../runtime-modules/defi/setswap/dex" }
module-prices = { path = "../../runtime-modules/prices" }
module-transaction-payment = { path = "../../runtime-modules/transaction-payment" }

[features]
default = ["std"]
std = [
	"num_enum/std",
	"serde",
	"codec/std",
	"ethabi/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-scheduler/std",
	"pallet-collective/std",
	"pallet-membership/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	"orml-oracle/std",
	"orml-traits/std",
	"module-evm/std",
	"module-support/std",
	"primitives/std",
]
with-ethereum-compatibility = [
	"module-evm/with-ethereum-compatibility",
]
