[package]
license = "Apache-2.0 OR MIT"
name = "event-def-unused"
version = "0.1.0"
edition = "2021"

[dependencies]
ink = { path = "../../../../crates/ink", default-features = false }

[features]
default = ["std"]
std = [
    "ink/std",
]
